name: HypixelCore
description: HypixelCore remake
main: me.ikeetjeop.hypixel.HypixelCore
version: 1.0
author: Ikeetjeop
depend: [Vault]
loadbefore: [Vault]
commands:
  joinalert:
    description: Disable/Enable join message
  spawn:
    description: ...
    aliases: [hub, lobby]
  help:
    description: ...
