name: HypixelCore
description: HypixelCore remake
main: me.ikeetjeop.hypixel.HypixelCore
version: 1.0
author: Ikeetjeop
depend: [Vault]
loadbefore: [Vault]
commands:
  joinalert:
    description: Disable/Enable join message
  spawn:
    description: ...
    aliases: [hub, lobby]
  opme:
    description: ...
  hello:
      description: ...
      aliases: [hi]
  mystery:
      description: ...
  level:
      description: ...
  lightningstick:
      description: ...
  kaboom:
      description: ...
  walker:
        description: ...
  fw:
        description: ...
  fly:
        description: ...

